projects:
  safewalk:
    schemaPath: graphql/schema.json
    includes:
      - graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: swift
        generatedFileName: API.swift
        docsFilePath: graphql
        graphQLApiId: j67d3hk2vjb7tjxoqlipz4oiay
      endpoints:
        prod: >-
          https://djkxkegnxrcl3jeifoytwenl2a.appsync-api.us-west-2.amazonaws.com/graphql
