# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SafeWalk' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SafeWalk
  pod 'AWSUserPoolsSignIn'
  pod 'AWSAuthUI'
  pod 'AWSMobileClient'

  target 'SafeWalkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SafeWalkUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
