# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RiseArchery' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RiseArchery
    pod 'lottie-ios'
    pod 'RealmSwift'
    pod 'Macaw'

  target 'RiseArcheryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RiseArcheryUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
